sudo: required

language: node_js
node_js:
  - "4"
  - "6"

env:
  - TEST_PLUGIN='plugins/default'
  - TEST_PLUGIN='plugins/meteor'
  - TEST_PLUGIN='plugins/mongo'
  - TEST_PLUGIN='plugins/docker'
  - TEST_PLUGIN='plugins/proxy'

services:
  - docker

before_script:
  - echo 'DOCKER_OPTS="--storage-driver=devicemapper"' | sudo tee --append /etc/default/docker >/dev/null && sudo service docker restart

script: npm run test -- --plugin="$TEST_PLUGIN"
